# Commands to run after login
after-login-command = []

# Commands to run after AeroSpace startup
after-startup-command = []

# Start AeroSpace at login
start-at-login = true

# Enable normalization rules
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# Layout and orientation settings
accordion-padding = 30
default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'

# Mouse follows focus on monitor change
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

on-focus-changed = ['move-mouse monitor-lazy-center']

# This disables macs default keybind for cmd-h and cmd-alt-h, to hide apps that are focused
# uncommenting this line and line 49 has the same effect

# automatically-unhide-macos-hidden-apps = true

# [exec]                   # Again, you don't need to copy all config sections to your config.
# inherit-env-vars = true  # If you don't touch "exec" section,
# [exec.env-vars]          # it will fallback to "default-config.toml"
# PATH = '/opt/homebrew/bin:/opt/homebrew/sbin:${PATH}'

# Key mapping preset
[key-mapping]
preset = 'qwerty'

# Gaps settings
[gaps]
outer.bottom =     [{monitor.'^built-in retina display$' = 10 }, 10]
outer.top =        [{monitor.'^built-in retina display$' = 10 }, 22]
outer.left =       13
outer.right =      13
inner.horizontal = 10
inner.vertical =   10

# Binding Modes - Main mode
[mode.main.binding]
# cmd-h = [] # Disable "hide application"
# cmd-alt-h = [] # Disable "hide others"

# Layout shortcuts
alt-slash = 'layout tiles horizontal vertical'
alt-comma = 'layout accordion horizontal vertical'
# Resets all apps to their dedicated workspaces, configure apps and workspaces inside the script
alt-r = 'exec-and-forget ~/aerospace.sh reset-workspaces'
# REPLACE for path to your terminal, MacOS paths are very deceptive, I had to look a lot to find Wezterm :@
alt-enter = 'exec-and-forget open -n /Applications/Wezterm.app'

# Focus navigation shortcuts
alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

# Move window shortcuts
alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

# Resize window shortcuts
alt-shift-minus = 'resize smart -50'
alt-shift-equal = 'resize smart +50'

alt-1 = 'workspace --auto-back-and-forth 1'
alt-2 = 'workspace --auto-back-and-forth 2'
alt-3 = 'workspace --auto-back-and-forth 3'
alt-4 = 'workspace --auto-back-and-forth 4'
alt-5 = 'workspace --auto-back-and-forth 5'
alt-6 = 'workspace --auto-back-and-forth 6'
alt-7 = 'workspace --auto-back-and-forth 7'
alt-8 = 'workspace --auto-back-and-forth 8'
alt-9 = 'workspace --auto-back-and-forth 9'
alt-a = 'workspace --auto-back-and-forth Browser:Personal' # In your config, you can drop workspace bindings that you don't need
alt-e = 'workspace --auto-back-and-forth Email'
alt-w = 'workspace --auto-back-and-forth Browser:Work'
alt-t = 'workspace --auto-back-and-forth Terminal'
alt-c = 'workspace --auto-back-and-forth code_editor'
alt-f = 'fullscreen'
alt-n = 'workspace --auto-back-and-forth Notes'
alt-m = 'workspace --auto-back-and-forth Messaging'

# See: https://nikitabobko.github.io/AeroSpace/commands#move-node-to-workspace
alt-shift-1 = 'move-node-to-workspace 1'
alt-shift-2 = 'move-node-to-workspace 2'
alt-shift-3 = 'move-node-to-workspace 3'
alt-shift-4 = 'move-node-to-workspace 4'
alt-shift-5 = 'move-node-to-workspace 5'
alt-shift-6 = 'move-node-to-workspace 6'
alt-shift-7 = 'move-node-to-workspace 7'
alt-shift-8 = 'move-node-to-workspace 8'
alt-shift-9 = 'move-node-to-workspace 9'
alt-shift-a = 'move-node-to-workspace Browser:Personal' # In your config, you can drop workspace bindings that you don't need
alt-shift-e = 'move-node-to-workspace Email'
alt-shift-w = 'move-node-to-workspace Browser:Work'
alt-shift-t = 'move-node-to-workspace Terminal'
alt-shift-c = 'move-node-to-workspace code_editor'
alt-shift-n = 'move-node-to-workspace Notes'
alt-shift-m = 'move-node-to-workspace Messaging'

# Bring forth other workspaces to your current workspace
ctrl-alt-1 = 'exec-and-forget ~/aerospace.sh bring-workspace 1'
ctrl-alt-2 = 'exec-and-forget ~/aerospace.sh bring-workspace 2'
ctrl-alt-3 = 'exec-and-forget ~/aerospace.sh bring-workspace 3'
ctrl-alt-4 = 'exec-and-forget ~/aerospace.sh bring-workspace 4'
ctrl-alt-5 = 'exec-and-forget ~/aerospace.sh bring-workspace 5'
ctrl-alt-6 = 'exec-and-forget ~/aerospace.sh bring-workspace 6'
ctrl-alt-7 = 'exec-and-forget ~/aerospace.sh bring-workspace 7'
ctrl-alt-8 = 'exec-and-forget ~/aerospace.sh bring-workspace 8'
ctrl-alt-9 = 'exec-and-forget ~/aerospace.sh bring-workspace 9'
ctrl-alt-a = 'exec-and-forget ~/aerospace.sh bring-workspace Browser:Personal' 
ctrl-alt-e = 'exec-and-forget ~/aerospace.sh bring-workspace Email'
ctrl-alt-w = 'exec-and-forget ~/aerospace.sh bring-workspace Browser:Work'
ctrl-alt-t = 'exec-and-forget ~/aerospace.sh bring-workspace Terminal'
ctrl-alt-c = 'exec-and-forget ~/aerospace.sh bring-workspace code_editor'
ctrl-alt-n = 'exec-and-forget ~/aerospace.sh bring-workspace Notes'
ctrl-alt-m = 'exec-and-forget ~/aerospace.sh bring-workspace Messaging'

# go back to prev workspace
alt-tab = 'workspace-back-and-forth'
# send workspace to monitor
alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

# Special mode: Service(this name can be anything like Dog, Cat), press this keybind to go into the mode defined below
alt-shift-semicolon = 'mode service'

# Service mode bindings
[mode.service.binding]
# reload config and go to main mode
esc = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main']
f = ['layout floating tiling', 'mode main']
backspace = ['close-all-windows-but-current', 'mode main']

# Application assignments to workspaces

[[on-window-detected]]
if.app-id = 'com.microsoft.VSCode'
run = ['move-node-to-workspace code_editor']

[[on-window-detected]]
if.workspace = '6'
check-further-callbacks = true
run = ['layout floating']

[[on-window-detected]]
if.app-id = 'company.thebrowser.Browser'
run = ['layout tiling', 'move-node-to-workspace Browser:Personal']

[[on-window-detected]]
if.app-id = 'com.github.wez.wezterm'
run = ['layout tiling', 'move-node-to-workspace Terminal']
[[on-window-detected]]
if.app-id = 'md.obsidian'
run = ['layout tiling', 'move-node-to-workspace Notes']

[[on-window-detected]]
if.app-id = 'com.apple.finder'
run = ['layout floating']

[[on-window-detected]]
if.app-id = 'com.apple.systempreferences'
run = ['layout floating']

[[on-window-detected]]
if.app-id = 'com.microsoft.teams2'              
run = ['move-node-to-workspace Messaging']  

[[on-window-detected]]
if.app-id = 'com.microsoft.Outlook'              
run = ['move-node-to-workspace Email']  


[[on-window-detected]]
if.app-id = 'com.microsoft.edgemac'              
run = ['move-node-to-workspace Browser:Work']  

[[on-window-detected]]
check-further-callbacks = true
run = ['layout floating', 'move-node-to-workspace 6'] 

# Uncomment these lines if you use a monitor, then if you're in a monitor you can grab workspaces in other monitors to
# your current focused monitor

# shift-ctrl-alt-1 = 'exec-and-forget ~/aerospace.sh bring-workspace 1'
# shift-ctrl-alt-2 = 'exec-and-forget ~/aerospace.sh bring-workspace 2'
# shift-ctrl-alt-3 = 'exec-and-forget ~/aerospace.sh bring-workspace 3'
# shift-ctrl-alt-4 = 'exec-and-forget ~/aerospace.sh bring-workspace 4'
# shift-ctrl-alt-5 = 'exec-and-forget ~/aerospace.sh bring-workspace 5'
# shift-ctrl-alt-6 = 'exec-and-forget ~/aerospace.sh bring-workspace 6'
# shift-ctrl-alt-7 = 'exec-and-forget ~/aerospace.sh bring-workspace 7'
# shift-ctrl-alt-8 = 'exec-and-forget ~/aerospace.sh bring-workspace 8'
# shift-ctrl-alt-9 = 'exec-and-forget ~/aerospace.sh bring-workspace 9'
# shift-ctrl-alt-a = 'exec-and-forget ~/aerospace.sh bring-workspace Browser:Personal' 
# shift-ctrl-alt-e = 'exec-and-forget ~/aerospace.sh bring-workspace Email'
# shift-ctrl-alt-w = 'exec-and-forget ~/aerospace.sh bring-workspace Browser:Work'
# shift-ctrl-alt-t = 'exec-and-forget ~/aerospace.sh bring-workspace Terminal'
# shift-ctrl-alt-c = 'exec-and-forget ~/aerospace.sh bring-workspace code_editor'
# shift-ctrl-alt-n = 'exec-and-forget ~/aerospace.sh bring-workspace Notes'
# shift-ctrl-alt-m = 'exec-and-forget ~/aerospace.sh bring-workspace Messaging'

